.PHONY: clean All

All:
	@echo "----------Building project:[ functions1 - Debug ]----------"
	@cd "functions1" && "$(MAKE)" -f  "functions1.mk"
clean:
	@echo "----------Cleaning project:[ functions1 - Debug ]----------"
	@cd "functions1" && "$(MAKE)" -f  "functions1.mk" clean
